"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const modulos_1 = require("./modulos");
const modulos_2 = require("./modulos");
const modulos_3 = require("./modulos");
const modulos_4 = require("./modulos");
var y = (0, modulos_2.somar)(20, 10);
var x = (0, modulos_1.subtrair)(20, 10);
var z = (0, modulos_3.dividir)(20, 10);
var v = (0, modulos_4.multiplicar)(20, 10);
